@startuml

' verhindere Probleme mit gewinkelten Krähenfüßen
skinparam linetype ortho
 
' package Dummy{
' entity Entität01 {
'    optionales Attribut
'    **optionales fettes Attribut**
'    * **vorgeschriebens fettes Attribut**
' }
' 
' entity Entität01 {
'    optionales Attribut : text
'    **optionales fettes Attribut** nummer <<auto>>
'    * **vorgeschriebens fettes Attribut**
' }
' Entität01 }|..|| Entität02
' Entität03 }o..o| Entität04
' Entität05 ||--o{ Entität06
' Entität07 |o--|| Entität08
' }
 
 ' TODO:
 ' Vervollständigen im Sinne von: https://github.com/gematik/spec-ISiK-Medikation/blob/rc/main-stufe-4/Material/docs/Medikation%20Abgleich%20bestehende%20Spezifikationen.xlsx

namespace ISiK_Basis {
   class Basismodul_Stufe_3 <<(M,#FFDC36)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v3/~introduction ISiK Basis Stufe 3]]
   }
   class ISiKPatient <Patient><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v3/isikpatient ISiK Patient]]
   }
   class ISiKKontaktGesundheitseinrichtung <Encounter><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v3/isikkontaktgesundheitseinrichtung ISiK Kontakt Gesundheitseinrichtung]]
   }
   class ISiKPractitioner <Practitioner><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v3/isikpersonimgesundheitsberuf ISiK Person im Gesundheitsberuf]]
   }
   class ISiKDiagnose <Condition><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v3/isikdiagnose ISiK Diagnose]]
   }
   class ISiKProzedur <Procedure><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v3/isikprozedur ISiK Prozedur]]
   }
   class ISiKAngehoeriger <RelatedPerson><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v3/isikangehoeriger ISiK Angehoeriger]]
   }  
   class  ISiKAllergie <AllergyIntolerance><<(P,#8DA5C4)>>{
      TBD

      **Beginn**
      **Abklingen**
      **Lebensphase**
   }
   class  ISiKDiagnose <Condition><<(P,#8DA5C4)>>{
      --
      --
      **klinischer Status**
      **Verifikationsstatus**
      **Typ**
      **Kategorie**
      **Kritikalität**
      **Code**
   }
}


namespace ISiK_Medikation {
   class  ISiKMedikament <Medication><<(P,#8DA5C4)>>{
      id
      code
      |_ coding­
         |_ PZN : **Pattern**
         |_ ATC-DE : **Pattern**
         |_ WG14 : **Pattern**
      |_ text
      status
      manufacturer : Reference (**Organization**)
      |_ display
      form 
      |_ coding
         |_ EDQM : **Binding**
      amount
      |_ numerator : **Pattern**
         |_ value
         |_ unit
         |_ system
         |_ code
      |_ denominator : **Pattern**
         |_ value
         |_ unit
         |_ system
         |_ code
      ingredient
      |_ extension
         |_ Wirkstofftyp : **Extension**
      |_ item[x]
         |_ itemCodeableConcept
            |_ coding­
               |_ ASK : **Pattern**
               |_ PZN : **Pattern**
               |_ ATC-DE : **Pattern**
               |_ WG14 : **Pattern**
            |_ text
         |_ itemReference : Reference (**Substance** | **Medication**)
            |_ reference
      |_ isActive
      |_ strength
         |_ numerator : **Pattern**
         '   |_ value
         '   |_ unit
         '   |_ system
         '   |_ code
         |_ denominator : **Pattern**
         '   |_ value
         '   |_ unit
         '   |_ system
         '   |_ code
      batch
      |_ lotNumber

   }
   'ISiKMedikation::itemReference --> ISiKMedikation

   class ISiKMedikationsInformation <MedicationStatement><<(P,#8DA5C4)>>{
      id	
      partOf : Reference (**MedicationAdministration** | **MedicationDispense** |\n **MedicationStatement** | **Procedure** | Observation)
      status
      medication[x]
      |_ medicationCodeableConcept
         |_ coding­
            |_ PZN : **Pattern**
            |_ ATC-DE : **Pattern**
            |_ WG14 : **Pattern**
         text
      |_ medicationReference Reference (**Medication**)
         |_ reference
      subject : Reference (**Patient**)
         |_ reference
      context : Reference (**Encounter** | EpisodeOfCare)
         |_ reference
      effective[x]
      |_ effectiveDateTime
      |_ effectivePeriod
         |_ start
         |_ end
      dateAsserted
      reasonCode
      |_ coding
         '|_ system
         '|_ code
         '|_ display
      |_ text
      reasonReference : Reference (**Condition** | Observation | DiagnosticReport)
      |_ reference
      note
      |_ text
      dosage
      |_ text
      |_ patientInstruction
      |_ timing
         |_ event
         |_ repeat
      |_ site
      |_	coding
      |_ text
      |_route
         |_	coding
            |_	EDQM : **Pattern**
            |_	SNOMED-CT : **Pattern**
         |_ text	
      |_ doseAndRate
         '|_ dose[x]
         '   |_ doseRange
         '   |_ doseQuantity
         '|_ rate[x]
         '   |_ rateRatio
         '   |_ rateRange
         '   |_ rateQuantity
      |_ maxDosePerPeriod
         |_ numerator : **Pattern**
         |_ denominator : **Pattern**
      |_ maxDosePerAdministration : **SimpleQuantity**
         '|_ value
         '|_ unit
         '|_ system
         '|_ code
   }
   'ISiKMedikationsInformation::medicationReference ---> ISiKMedikation
   
   class  ISiKMedikationsListe <List><<(P,#8DA5C4)>>{
      id
      status : **Binding**
      mode : **Binding**
      code
      |_ coding
         |_ medications : **Pattern**
            |_ system
            |_ code
            |_ display
      subject : Reference (**Patient**)
      |_ reference
      encounter : Reference (**Encounter**)
      |_ reference
      date
      entry
      |_ date
      |_ item : Reference (**MedicationStatement**)
         |_ reference
   }
   'ISiKMedikationsListe::item --> ISiKMedikationsInformation

   class ISiKMedikationsVerabreichung <MedicationAdministration><<(P,#8DA5C4)>>{
      id
      status
      subject : Reference (**Patient**)
      |_ reference
      context : Reference (**Encounter** | EpisodeOfCare)
      |_ reference
      effective[x]
      |_ effectiveDateTime
      |_ effectivePeriod
         |_ start
         |_ end
      peformer
      |_ actor
         |_ reference
      reasonReference : Reference (**Condition** | Observation |\n DiagnosticReport)
      |_ reference
      note : **Annotation**
      |_ text
      dosage
      |_ text
      |_ site
         |_	coding
            |_	SNOMED-CT : **Pattern**
         |_ text	
      |_ route
         |_	coding
            |_	EDQM : **Pattern**
            |_	SNOMED-CT : **Pattern**
         |_ text	
      |_ dose
      |_ rate[x]
         |_ rateRatio : **Ratio**
            |_ numerator : **Pattern**
            |_ denominator : **Pattern**
         |_ rateQuantity : **SimpleQuantity**
   }

   class ISiKMedikationsVerordnung <MedicationRequest><<(P,#8DA5C4)>>{
      id
      status
      intent
      <s>doNotPerform</s>
      medication[x]
      |_ medicationCodeableConcept
          |_ coding­
               |_ PZN : **Pattern**
               |_ ATC-DE : **Pattern**
               |_ WG14 : **Pattern**
            |_ text
      |_ medicationReference (**Medication**)
         |_ reference
      subject : Reference (**Patient**)
      |_ reference
      encounter : Reference (**Encounter**)
      |_ reference
      authoredOn
      requester : Reference (**Practitioner** | PractitionerRole |\n Organization | **Patient** | **RelatedPerson** | Device)
      |_ reference
      note : **Annotation**
      |_ text
      dosageInstruction
      |_ text
      |_ patientInstruction
      |_ timing	
         |_ event
         |_ repeat
      |_ site
         |_	coding
            |_	SNOMED-CT : **Pattern**
         |_ text	
      |_ route
         |_	coding
            |_	EDQM : **Pattern**
            |_	SNOMED-CT : **Pattern**
         |_ text	
      |_ doseAndRate
         '|_ dose[x]
         '   |_ doseRange
         '   |_ doseQuantity
         '|_ rate[x]
         '   |_ rateRatio
         '   |_ rateRange
         '   |_ rateQuantity
      |_ maxDosePerPeriod
         |_ numerator : **Pattern**
         |_ denominator : **Pattern**
      |_ maxDosePerAdministration : **SimpleQuantity**
         '|_ value
         '|_ unit
         '|_ system
         '|_ code
      dispenseRequest
      |_ quantity
      substitution
      |_ allowed[x]
         |_ allowedBoolean
   }

   class ISiKMedikationTransaction <Bundle><<(P,#8DA5C4)>>{
      type : BundleType.**Transaction**
      entry
      |_ <s>link</s>
      |_ fullUrl
      |_ resource
      |_ <s>search</s>
      |_ **request**
         |_ method
         |_ url
      |_ <s>response</s>
   }
   class ISiKMedikationTransactionResponse <Bundle><<(P,#8DA5C4)>>{
      type : BundleType.**Response**
      entry
      |_ <s>link</s>
      |_ fullUrl
      |_ resource
      |_ <s>search</s>
      |_ <s>request</s>
      |_ **response**
         |_ status
         |_ location
         |_ outcome
   }
   class SctRouteOfAdministration <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-medikation-v3/sctrouteofadministration SNOMED CT Route Of Administration]]
      Beeinhaltet Codes aus SNOMED CT bei denen das \nConcept 284009009 (Route Of Administration) ist
      [[https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/80147 SNOMED_CT 284009009]]
      --
      codes : **$CS-SCT** 
   }
}

package "ISiK-Labor (MVP)"{
   class  ISiKLaborErgebnis <Observation><<(P,#8DA5C4)>>{
      TBD
      ..Nierenfunktion..
         **GFR**
         **Serumkreation**
         **Risikomeldung**
      ..
   }
}

namespace R4_Core {
   class Foundation_Modul <<(M,#FFAAAA)>>{
      Dokumentation auf HL7 Org
      [[https://hl7.org/fhir/R4/ HL7 FHIR R4 Core Foundation]]
   }
   
   class AllergyIntoleranceCategory <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[https://hl7.org/fhir/R4/valueset-allergy-intolerance-category.html Allergy Intolerance Category]]
      Das ValueSet entsprechende Standardset und beeinhatet das komplette Code System der Allergy Intolerance Category
      [[https://hl7.org/fhir/R4/codesystem-allergy-intolerance-category.html Zugehöriges Code System of Category]]
   }
   class AllergyIntoleranceCriticality <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[https://hl7.org/fhir/R4/valueset-allergy-intolerance-criticality.html Allergy Intolerance Criticality]]
      Das ValueSet entsprechende Standardset und beeinhatet das komplette Code System der Allergy Intolerance Criticality
      [[https://hl7.org/fhir/R4/codesystem-allergy-intolerance-criticality.html Zugehöriges Code System of Criticality]]
   }
   class ReactionEventSeverity <ValueSet><<(V,#8DA5C4)>>{
      Dokumentation auf HL7 Org 
      [[https://hl7.org/fhir/R4/valueset-reaction-event-severity.html Reaction Eventu Severity]]
      Das ValueSet entsprechende Standardset und beeinhatet das komplette Code System der Allergy Intolerance Severity
      [[https://hl7.org/fhir/R4/codesystem-reaction-event-severity.html Zugehöriges Code System of Severity]]
   }
}


@enduml